name: Tag Render Production Deployment

on:
  push:
    branches:
      - main  # Change if your production branch is something else

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Register Render Deployment with GitHub
        uses: actions/github-script@v7
        with:
          script: |
            const deployment = await github.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.ref,
              required_contexts: [],
              environment: 'production',
              transient_environment: false,
              production_environment: true,
              auto_merge: false
            });

            await github.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: deployment.data.id,
              state: 'success',
              environment_url: 'https://crime-analysis-pusn.onrender.com',  # 🔁 Replace with your actual Render URL
              log_url: 'https://dashboard.render.com/web/srv-cpg9lm7109ks73carrv0/logs',  # Optional
              description: 'Deployed to Render'
            });
